### ISSUE TITLE
Api Info leads to extension readme in old location

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/boltcards#13]
Link seems right though
https://github.com/lnbits/boltcards/blob/a5b72361174e1c5d36c29ec40f7883cc1c92b369/templates/boltcards/_api_docs.html#L15

<img width="326" alt="Bildschirmfoto 2023-08-13 um 20 52 32" src="https://github.com/lnbits/boltcards/assets/63317640/d6ea3ae8-c395-40e1-9a73-a13c58ceb8cb">
**

<img width="414" alt="Bildschirmfoto 2023-08-13 um 20 52 20" src="https://github.com/lnbits/boltcards/assets/63317640/d05f0726-a768-4ec2-807c-e6c383512d98">
**

<img width="1253" alt="Bildschirmfoto 2023-08-13 um 20 55 01" src="https://github.com/lnbits/boltcards/assets/63317640/af973245-aadb-4949-8a48-f324b12720d9">

**Comment by dni** [comment]
yes it was fixed but not released yet. trying to release now

**Comment by dni** [comment]
https://github.com/lnbits/boltcards/releases/tag/0.0.2
