### ISSUE TITLE
Unable to delete a card from the UI

### ISSUE THREAD

**Issue by Amperstrand** [lnbits/boltcards#44]
To reproduce:
 - create a card
 -  try to delete it

"DELETE THE CARD" button does nothing. Just closes the window.

This makes it impossible to delete a card from an account

lnbits 1.0.0-rc6

**Comment by CabtonWithaK** [comment]
I have the same problem and it is quite a painful bug because it is currently impossible to reuse cards:
Since the card is not removed, the Card's UID can also not be reused. 

![error_deleting_cards](https://github.com/user-attachments/assets/9df4e531-b979-4fda-9459-35d51e6d6090)
