### ISSUE TITLE
Bad links from hashtag in wallet transaction history

### ISSUE THREAD

**Issue by Perlover** [lnbits/boltcards#7]
Hello,

_LNBits v0.10.9 (current branch from source)_

When I use Bolt cards your extension makes hashtag `#bolcard` in a transaction history in a bound wallet.
When I click by hashtag I am redirected to `https://mydomain.com/boltcard/?usr=....` but real links for bolt cards are `https://mydomain.com/`**`boltcards`**`/?usr=....`

I think it's bug of your extension. Or hashtag should be as `#boldcards` not `#bolcard` if it's an embeded algorithm of a redirect map.

**Comment by gorrdy** [comment]
This is really true. I can confirm the link is not working.
